// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	authpb "github.com/mmrgreenteaa/user-management-service/internal/gen/proto/auth"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"sync"
)

// Ensure, that AuthServiceClientMock does implement AuthServiceClient.
// If this is not the case, regenerate this file with moq.
var _ AuthServiceClient = &AuthServiceClientMock{}

// AuthServiceClientMock is a mock implementation of AuthServiceClient.
//
//	func TestSomethingThatUsesAuthServiceClient(t *testing.T) {
//
//		// make and configure a mocked AuthServiceClient
//		mockedAuthServiceClient := &AuthServiceClientMock{
//			LoginFunc: func(ctx context.Context, in *authpb.UserInfoRequest, opts ...grpc.CallOption) (*authpb.SignInUserResponse, error) {
//				panic("mock out the Login method")
//			},
//			LogoutFunc: func(ctx context.Context, in *authpb.LogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
//				panic("mock out the Logout method")
//			},
//			RefreshTokenFunc: func(ctx context.Context, in *authpb.RefreshRequest, opts ...grpc.CallOption) (*authpb.SignInUserResponse, error) {
//				panic("mock out the RefreshToken method")
//			},
//			VerifyAccessFunc: func(ctx context.Context, in *authpb.AccessRequest, opts ...grpc.CallOption) (*authpb.VerifyAccessResponse, error) {
//				panic("mock out the VerifyAccess method")
//			},
//		}
//
//		// use mockedAuthServiceClient in code that requires AuthServiceClient
//		// and then make assertions.
//
//	}
type AuthServiceClientMock struct {
	// LoginFunc mocks the Login method.
	LoginFunc func(ctx context.Context, in *authpb.UserInfoRequest, opts ...grpc.CallOption) (*authpb.SignInUserResponse, error)

	// LogoutFunc mocks the Logout method.
	LogoutFunc func(ctx context.Context, in *authpb.LogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)

	// RefreshTokenFunc mocks the RefreshToken method.
	RefreshTokenFunc func(ctx context.Context, in *authpb.RefreshRequest, opts ...grpc.CallOption) (*authpb.SignInUserResponse, error)

	// VerifyAccessFunc mocks the VerifyAccess method.
	VerifyAccessFunc func(ctx context.Context, in *authpb.AccessRequest, opts ...grpc.CallOption) (*authpb.VerifyAccessResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// Login holds details about calls to the Login method.
		Login []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *authpb.UserInfoRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// Logout holds details about calls to the Logout method.
		Logout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *authpb.LogoutRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// RefreshToken holds details about calls to the RefreshToken method.
		RefreshToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *authpb.RefreshRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// VerifyAccess holds details about calls to the VerifyAccess method.
		VerifyAccess []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *authpb.AccessRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
	}
	lockLogin        sync.RWMutex
	lockLogout       sync.RWMutex
	lockRefreshToken sync.RWMutex
	lockVerifyAccess sync.RWMutex
}

// Login calls LoginFunc.
func (mock *AuthServiceClientMock) Login(ctx context.Context, in *authpb.UserInfoRequest, opts ...grpc.CallOption) (*authpb.SignInUserResponse, error) {
	if mock.LoginFunc == nil {
		panic("AuthServiceClientMock.LoginFunc: method is nil but AuthServiceClient.Login was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *authpb.UserInfoRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	return mock.LoginFunc(ctx, in, opts...)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedAuthServiceClient.LoginCalls())
func (mock *AuthServiceClientMock) LoginCalls() []struct {
	Ctx  context.Context
	In   *authpb.UserInfoRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *authpb.UserInfoRequest
		Opts []grpc.CallOption
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// Logout calls LogoutFunc.
func (mock *AuthServiceClientMock) Logout(ctx context.Context, in *authpb.LogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	if mock.LogoutFunc == nil {
		panic("AuthServiceClientMock.LogoutFunc: method is nil but AuthServiceClient.Logout was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *authpb.LogoutRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockLogout.Lock()
	mock.calls.Logout = append(mock.calls.Logout, callInfo)
	mock.lockLogout.Unlock()
	return mock.LogoutFunc(ctx, in, opts...)
}

// LogoutCalls gets all the calls that were made to Logout.
// Check the length with:
//
//	len(mockedAuthServiceClient.LogoutCalls())
func (mock *AuthServiceClientMock) LogoutCalls() []struct {
	Ctx  context.Context
	In   *authpb.LogoutRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *authpb.LogoutRequest
		Opts []grpc.CallOption
	}
	mock.lockLogout.RLock()
	calls = mock.calls.Logout
	mock.lockLogout.RUnlock()
	return calls
}

// RefreshToken calls RefreshTokenFunc.
func (mock *AuthServiceClientMock) RefreshToken(ctx context.Context, in *authpb.RefreshRequest, opts ...grpc.CallOption) (*authpb.SignInUserResponse, error) {
	if mock.RefreshTokenFunc == nil {
		panic("AuthServiceClientMock.RefreshTokenFunc: method is nil but AuthServiceClient.RefreshToken was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *authpb.RefreshRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockRefreshToken.Lock()
	mock.calls.RefreshToken = append(mock.calls.RefreshToken, callInfo)
	mock.lockRefreshToken.Unlock()
	return mock.RefreshTokenFunc(ctx, in, opts...)
}

// RefreshTokenCalls gets all the calls that were made to RefreshToken.
// Check the length with:
//
//	len(mockedAuthServiceClient.RefreshTokenCalls())
func (mock *AuthServiceClientMock) RefreshTokenCalls() []struct {
	Ctx  context.Context
	In   *authpb.RefreshRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *authpb.RefreshRequest
		Opts []grpc.CallOption
	}
	mock.lockRefreshToken.RLock()
	calls = mock.calls.RefreshToken
	mock.lockRefreshToken.RUnlock()
	return calls
}

// VerifyAccess calls VerifyAccessFunc.
func (mock *AuthServiceClientMock) VerifyAccess(ctx context.Context, in *authpb.AccessRequest, opts ...grpc.CallOption) (*authpb.VerifyAccessResponse, error) {
	if mock.VerifyAccessFunc == nil {
		panic("AuthServiceClientMock.VerifyAccessFunc: method is nil but AuthServiceClient.VerifyAccess was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *authpb.AccessRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockVerifyAccess.Lock()
	mock.calls.VerifyAccess = append(mock.calls.VerifyAccess, callInfo)
	mock.lockVerifyAccess.Unlock()
	return mock.VerifyAccessFunc(ctx, in, opts...)
}

// VerifyAccessCalls gets all the calls that were made to VerifyAccess.
// Check the length with:
//
//	len(mockedAuthServiceClient.VerifyAccessCalls())
func (mock *AuthServiceClientMock) VerifyAccessCalls() []struct {
	Ctx  context.Context
	In   *authpb.AccessRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *authpb.AccessRequest
		Opts []grpc.CallOption
	}
	mock.lockVerifyAccess.RLock()
	calls = mock.calls.VerifyAccess
	mock.lockVerifyAccess.RUnlock()
	return calls
}
