// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	usermepb "github.com/mmrgreenteaa/user-management-service/internal/gen/proto/user_manegement"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"sync"
)

// Ensure, that UserManagementClientMock does implement UserManagementClient.
// If this is not the case, regenerate this file with moq.
var _ UserManagementClient = &UserManagementClientMock{}

// UserManagementClientMock is a mock implementation of UserManagementClient.
//
//	func TestSomethingThatUsesUserManagementClient(t *testing.T) {
//
//		// make and configure a mocked UserManagementClient
//		mockedUserManagementClient := &UserManagementClientMock{
//			DeleteUserFunc: func(ctx context.Context, in *usermepb.DeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
//				panic("mock out the DeleteUser method")
//			},
//			EditLoginFunc: func(ctx context.Context, in *usermepb.UserLoginEditReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
//				panic("mock out the EditLogin method")
//			},
//			RegistrationUserFunc: func(ctx context.Context, in *usermepb.UserRegistrationReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
//				panic("mock out the RegistrationUser method")
//			},
//			VerifyCredentialsFunc: func(ctx context.Context, in *usermepb.UserValidRequest, opts ...grpc.CallOption) (*usermepb.UserValidResponse, error) {
//				panic("mock out the VerifyCredentials method")
//			},
//		}
//
//		// use mockedUserManagementClient in code that requires UserManagementClient
//		// and then make assertions.
//
//	}
type UserManagementClientMock struct {
	// DeleteUserFunc mocks the DeleteUser method.
	DeleteUserFunc func(ctx context.Context, in *usermepb.DeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error)

	// EditLoginFunc mocks the EditLogin method.
	EditLoginFunc func(ctx context.Context, in *usermepb.UserLoginEditReq, opts ...grpc.CallOption) (*emptypb.Empty, error)

	// RegistrationUserFunc mocks the RegistrationUser method.
	RegistrationUserFunc func(ctx context.Context, in *usermepb.UserRegistrationReq, opts ...grpc.CallOption) (*emptypb.Empty, error)

	// VerifyCredentialsFunc mocks the VerifyCredentials method.
	VerifyCredentialsFunc func(ctx context.Context, in *usermepb.UserValidRequest, opts ...grpc.CallOption) (*usermepb.UserValidResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteUser holds details about calls to the DeleteUser method.
		DeleteUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *usermepb.DeleteReq
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// EditLogin holds details about calls to the EditLogin method.
		EditLogin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *usermepb.UserLoginEditReq
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// RegistrationUser holds details about calls to the RegistrationUser method.
		RegistrationUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *usermepb.UserRegistrationReq
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
		// VerifyCredentials holds details about calls to the VerifyCredentials method.
		VerifyCredentials []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// In is the in argument value.
			In *usermepb.UserValidRequest
			// Opts is the opts argument value.
			Opts []grpc.CallOption
		}
	}
	lockDeleteUser        sync.RWMutex
	lockEditLogin         sync.RWMutex
	lockRegistrationUser  sync.RWMutex
	lockVerifyCredentials sync.RWMutex
}

// DeleteUser calls DeleteUserFunc.
func (mock *UserManagementClientMock) DeleteUser(ctx context.Context, in *usermepb.DeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	if mock.DeleteUserFunc == nil {
		panic("UserManagementClientMock.DeleteUserFunc: method is nil but UserManagementClient.DeleteUser was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *usermepb.DeleteReq
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockDeleteUser.Lock()
	mock.calls.DeleteUser = append(mock.calls.DeleteUser, callInfo)
	mock.lockDeleteUser.Unlock()
	return mock.DeleteUserFunc(ctx, in, opts...)
}

// DeleteUserCalls gets all the calls that were made to DeleteUser.
// Check the length with:
//
//	len(mockedUserManagementClient.DeleteUserCalls())
func (mock *UserManagementClientMock) DeleteUserCalls() []struct {
	Ctx  context.Context
	In   *usermepb.DeleteReq
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *usermepb.DeleteReq
		Opts []grpc.CallOption
	}
	mock.lockDeleteUser.RLock()
	calls = mock.calls.DeleteUser
	mock.lockDeleteUser.RUnlock()
	return calls
}

// EditLogin calls EditLoginFunc.
func (mock *UserManagementClientMock) EditLogin(ctx context.Context, in *usermepb.UserLoginEditReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	if mock.EditLoginFunc == nil {
		panic("UserManagementClientMock.EditLoginFunc: method is nil but UserManagementClient.EditLogin was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *usermepb.UserLoginEditReq
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockEditLogin.Lock()
	mock.calls.EditLogin = append(mock.calls.EditLogin, callInfo)
	mock.lockEditLogin.Unlock()
	return mock.EditLoginFunc(ctx, in, opts...)
}

// EditLoginCalls gets all the calls that were made to EditLogin.
// Check the length with:
//
//	len(mockedUserManagementClient.EditLoginCalls())
func (mock *UserManagementClientMock) EditLoginCalls() []struct {
	Ctx  context.Context
	In   *usermepb.UserLoginEditReq
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *usermepb.UserLoginEditReq
		Opts []grpc.CallOption
	}
	mock.lockEditLogin.RLock()
	calls = mock.calls.EditLogin
	mock.lockEditLogin.RUnlock()
	return calls
}

// RegistrationUser calls RegistrationUserFunc.
func (mock *UserManagementClientMock) RegistrationUser(ctx context.Context, in *usermepb.UserRegistrationReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	if mock.RegistrationUserFunc == nil {
		panic("UserManagementClientMock.RegistrationUserFunc: method is nil but UserManagementClient.RegistrationUser was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *usermepb.UserRegistrationReq
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockRegistrationUser.Lock()
	mock.calls.RegistrationUser = append(mock.calls.RegistrationUser, callInfo)
	mock.lockRegistrationUser.Unlock()
	return mock.RegistrationUserFunc(ctx, in, opts...)
}

// RegistrationUserCalls gets all the calls that were made to RegistrationUser.
// Check the length with:
//
//	len(mockedUserManagementClient.RegistrationUserCalls())
func (mock *UserManagementClientMock) RegistrationUserCalls() []struct {
	Ctx  context.Context
	In   *usermepb.UserRegistrationReq
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *usermepb.UserRegistrationReq
		Opts []grpc.CallOption
	}
	mock.lockRegistrationUser.RLock()
	calls = mock.calls.RegistrationUser
	mock.lockRegistrationUser.RUnlock()
	return calls
}

// VerifyCredentials calls VerifyCredentialsFunc.
func (mock *UserManagementClientMock) VerifyCredentials(ctx context.Context, in *usermepb.UserValidRequest, opts ...grpc.CallOption) (*usermepb.UserValidResponse, error) {
	if mock.VerifyCredentialsFunc == nil {
		panic("UserManagementClientMock.VerifyCredentialsFunc: method is nil but UserManagementClient.VerifyCredentials was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		In   *usermepb.UserValidRequest
		Opts []grpc.CallOption
	}{
		Ctx:  ctx,
		In:   in,
		Opts: opts,
	}
	mock.lockVerifyCredentials.Lock()
	mock.calls.VerifyCredentials = append(mock.calls.VerifyCredentials, callInfo)
	mock.lockVerifyCredentials.Unlock()
	return mock.VerifyCredentialsFunc(ctx, in, opts...)
}

// VerifyCredentialsCalls gets all the calls that were made to VerifyCredentials.
// Check the length with:
//
//	len(mockedUserManagementClient.VerifyCredentialsCalls())
func (mock *UserManagementClientMock) VerifyCredentialsCalls() []struct {
	Ctx  context.Context
	In   *usermepb.UserValidRequest
	Opts []grpc.CallOption
} {
	var calls []struct {
		Ctx  context.Context
		In   *usermepb.UserValidRequest
		Opts []grpc.CallOption
	}
	mock.lockVerifyCredentials.RLock()
	calls = mock.calls.VerifyCredentials
	mock.lockVerifyCredentials.RUnlock()
	return calls
}
