syntax = "proto3";

package github.com.mmrgreenteaa.user.management.service.interal.auth1;

option go_package = "github.com/mmrgreenteaa/user-management-service/interal/gen/auth;auth";

import "google/protobuf/empty.proto";


// Service responsible for user authentication and token management.
service Auth{ 
    // Authenticates a user using login and password.
    // Returns a pair of tokens (Access & Refresh) if credentials are valid.
    rpc Login(UserInfoRequest) returns (SignInUserResponse){}

    // Validates the provided Access Token.
    // Used by other microservices to check user authorization.
    rpc VerifyAccess(AccessRequest) returns(VerifyAccessResponse){}
    
    // Issues a new pair of tokens using a valid Refresh Token.
    // Should be called when Access Token expires.
    rpc RefreshToken(RefreshRequest) returns (SignInUserResponse){}
   
    // Revokes the user session associated with the provided Refresh Token.
    rpc Logout(LogoutRequest) returns (google.protobuf.Empty){}
}


message RefreshRequest{ 
  string refresh_token = 1; 
  string user_agent = 2;
  string ip = 3 ;
}

message AccessRequest{
  // access token
    string token = 1; 
}

message UserInfoRequest{ 
    string login = 1; 
    string password = 2; 
    string user_agent = 3; 
 string ip = 4; 
}

message SignInUserResponse {
  string access_token = 1;
  string refresh_token = 2;
}

message LogoutRequest {
  string refresh_token = 1; 
  string user_agent = 2;
  string ip = 3 ;
}

message VerifyAccessResponse {
  string user_id = 1;
  string login = 2;
}
