services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
    - "62580:62580"
    depends_on:
    - posgredb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    environment:
    -  AUTH_SECRET_KEY=23123
    - AUTH_PASSWORD_DB=QWERTY

  user_manager: 
     build:
      context: .
      dockerfile: Dockerfile.user-manager
     ports:
      - "62380:62380" 
  
  api_gateway:
    build:
        context: .
        dockerfile: Dockerfile.api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - redis
  posgredb:
    image: postgres:13-alpine
    environment:
       POSTGRES_USER:  postgres
       POSTGRES_PASSWORD: QWERTY
       POSTGRES_DB: auth_service 
    ports:
      - "5432:5432"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
