FROM golang:1.24.0-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /api_gateway ./cmd/api_gateway/main


FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /app/config/config.yaml /config/config.yaml

COPY --from=builder /api_gateway /api_gateway

EXPOSE 62480

# Run
CMD ["/api_gateway"]