syntax = "proto3";

package github.com.mmrgreenteaa.user.management.service.interal.user_manegement;

option go_package = "github.com/mmrgreenteaa/user-management-service/interal/gen/user_manegement;user_manegement";

import "google/protobuf/empty.proto";

message UserValidRequest{ 
    string login = 1; 
    string password =2; 
}

message UserValidResponse{
    string user_id = 1; 
} 

message UserRegistrationReq{
    string login = 1; 
    string password = 2;
    string email = 3;     
}

message UserLoginEditReq{
    string user_id = 1;
    string new_login = 2;  
}

message DeleteReq{ 
    string user_id = 1;  
}

// User data management service
service UserManagement{ 
    // Checks if the provided login and password are valid.
    rpc VerifyCredentials(UserValidRequest) returns (UserValidResponse){}
    // Registers a new user. Returns an error if the username is exits. 
    rpc RegistrationUser(UserRegistrationReq) returns (google.protobuf.Empty){}
    // Updates the user's login.
    rpc EditLogin(UserLoginEditReq) returns (google.protobuf.Empty){}
    // delete user.
    rpc DeleteUser(DeleteReq) returns (google.protobuf.Empty){}
};